# Generated by Django 3.2.13 on 2022-12-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='photo_accommodation',
            field=models.ImageField(blank=True, upload_to='places'),
        ),
        migrations.AddField(
            model_name='place',
            name='photo_facilities',
            field=models.ImageField(blank=True, upload_to='places'),
        ),
        migrations.AddField(
            model_name='place',
            name='photo_food',
            field=models.ImageField(blank=True, upload_to='places'),
        ),
        migrations.AddField(
            model_name='place',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='places'),
        ),
    ]
