# Generated by Django 3.2.13 on 2022-12-01 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_like_users'),
        ('accounts', '0002_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('imp_uid', models.CharField(max_length=50)),
                ('merchant_uid', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_places', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
