# Generated by Django 4.1.3 on 2022-11-29 08:25

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewimage",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, upload_to="reviews/"
            ),
        ),
    ]
