# Generated by Django 4.1.3 on 2022-11-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="likes_num",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
