# Generated by Django 4.1.3 on 2022-12-01 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_auto_20221201_1149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewimage",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_images",
                to="reviews.review",
            ),
        ),
    ]
